// Copyright 2024 N-GINN LLC. All rights reserved.

// Copyright (C) 2024  Gaijin Games KFT.  All rights reserved

#pragma once
#include "nau/utils/for_each.h"

#define NAU_EXPAND_ARG(x)                      x
#define NAU_FOR_EACH_ARG_1(ARG, WHAT, X)       WHAT(ARG, X)
#define NAU_FOR_EACH_ARG_2(ARG, WHAT, X, ...)  WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_1(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_3(ARG, WHAT, X, ...)  WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_2(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_4(ARG, WHAT, X, ...)  WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_3(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_5(ARG, WHAT, X, ...)  WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_4(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_6(ARG, WHAT, X, ...)  WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_5(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_7(ARG, WHAT, X, ...)  WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_6(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_8(ARG, WHAT, X, ...)  WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_7(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_9(ARG, WHAT, X, ...)  WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_8(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_10(ARG, WHAT, X, ...) WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_9(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_11(ARG, WHAT, X, ...) WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_10(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_12(ARG, WHAT, X, ...) WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_11(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_13(ARG, WHAT, X, ...) WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_12(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_14(ARG, WHAT, X, ...) WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_13(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_ARG_15(ARG, WHAT, X, ...) WHAT(ARG, X) NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_14(ARG, WHAT, __VA_ARGS__))
//... repeat as needed
#define NAU_FOR_EACH_ARG_NARG(...)             NAU_FOR_EACH_ARG_NARG_(__VA_ARGS__, NAU_FOR_EACH_ARG_RSEQ_N())
#define NAU_FOR_EACH_ARG_NARG_(...)            NAU_EXPAND_ARG(NAU_FOR_EACH_ARG_ARG_N(__VA_ARGS__))

#define NAU_FOR_EACH_ARG_ARG_N(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, N, ...) N

#define NAU_FOR_EACH_ARG_RSEQ_N()             15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0
#define NAU_CONCATENATE(x, y)                 x##y
#define NAU_FOR_EACH_ARG_(N, ARG, WHAT, ...)  NAU_EXPAND_ARG(CONCATENATE(NAU_FOR_EACH_ARG_, N)(ARG, WHAT, __VA_ARGS__))
#define NAU_FOR_EACH_WITH_ARG(WHAT, ARG, ...) __VA_OPT__(NAU_FOR_EACH_ARG_(NAU_FOR_EACH_ARG_NARG(__VA_ARGS__), ARG, WHAT, __VA_ARGS__))
